# Generated by Django 5.0.6 on 2024-06-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kirim_Turlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oylik', models.IntegerField(max_length=250)),
                ('avans', models.IntegerField(max_length=250)),
                ('kunlik_ish_haqqi', models.IntegerField(max_length=250)),
            ],
        ),
    ]
