# Generated by Django 5.0.6 on 2024-05-12 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0008_note_delete_appnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Hobby',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
