# Generated by Django 5.0.6 on 2024-06-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0011_kirim_turlari'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.IntegerField(max_length=300)),
                ('sana', models.DateTimeField(auto_now=True)),
                ('qayerdan', models.CharField(max_length=400)),
                ('oylik', models.BooleanField(default=False)),
                ('avans', models.BooleanField(default=False)),
                ('kunlik_ish_haqqi', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Kirim_Turlari',
        ),
    ]
