# Generated by Django 5.0.6 on 2024-06-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0012_kirim_delete_kirim_turlari'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirim',
            name='boshqa_valyuta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kirim',
            name='karta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kirim',
            name='naqt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kirim',
            name='summa',
            field=models.IntegerField(),
        ),
    ]
