# Generated by Django 5.0.6 on 2024-06-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0014_remove_kirim_avans_remove_kirim_boshqa_valyuta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirim',
            name='avans',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kirim',
            name='boshqa_valyuta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kirim',
            name='karta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kirim',
            name='kunlik_ish_haqqi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kirim',
            name='naqt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kirim',
            name='oylik',
            field=models.BooleanField(default=True),
        ),
    ]
