# Generated by Django 5.0.6 on 2024-06-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0017_alter_kirim_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kirim',
            name='summa',
        ),
        migrations.AddField(
            model_name='kirim',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='kirim',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='kirim',
            name='source_type',
            field=models.CharField(choices=[('monthly', 'Oylik'), ('advance', 'Avans'), ('daily', 'Kunlik ish haqi')], default='monthly', max_length=10),
        ),
    ]
