# Generated by Django 5.0.6 on 2024-06-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0018_remove_kirim_summa_kirim_amount_kirim_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirim',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
