# Generated by Django 5.0.6 on 2024-06-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0019_alter_kirim_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kirim',
            old_name='source',
            new_name='qayerdan',
        ),
        migrations.RenameField(
            model_name='kirim',
            old_name='date',
            new_name='sana',
        ),
        migrations.RenameField(
            model_name='kirim',
            old_name='amount',
            new_name='summa',
        ),
        migrations.RenameField(
            model_name='kirim',
            old_name='payment_type',
            new_name='tolov_turi',
        ),
        migrations.RemoveField(
            model_name='kirim',
            name='source_type',
        ),
        migrations.AddField(
            model_name='kirim',
            name='ish_haqqi_turi',
            field=models.CharField(choices=[('monthly', 'Oylik'), ('advance', 'Avans'), ('daily', 'Kunlik ish haqqi')], default='monthly', max_length=10),
        ),
    ]
