# Generated by Django 5.0.6 on 2024-06-10 11:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0020_rename_source_kirim_qayerdan_rename_date_kirim_sana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirim',
            name='sana',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
