# Generated by Django 5.0.6 on 2024-06-11 11:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0022_chiqim'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiqim',
            name='tolov_turi',
            field=models.CharField(choices=[('NAQT', 'Naqt'), ('KARTA', 'Karta')], default='NAQT', max_length=5),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='chiqim_turi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='qayerga',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='sana',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
