# Generated by Django 5.0.6 on 2024-06-11 11:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0023_chiqim_tolov_turi_alter_chiqim_chiqim_turi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiqim',
            name='sana',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
